on:
  push:

    tags:
      - 'v*' 

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: build artifacts
        run: make build-linux && make build-windows && make build-darwin
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
         GITHUB_TOKEN: ${{ github.token }}
        with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: ./bin/azblogfilter.linux-amd64.tar.gz
         asset_name: azblogfilter.linux-amd64.tar.gz
         asset_content_type: application/gzip
