name: vozved
on: 
 push
jobs:
 Build:
  runs-on: ubuntu-latest
  steps:
  
   - name: git clone
     uses: actions/checkout@v1
     
   - name: build vozved
     run: |
      cd vozved
      cmake -B applications
      cmake --build applications --target hello_world
      ./prog > prog.txt
      cat prog.txt
      cd ..
      
   - name: Upload Artifact v1
     uses: actions/upload-artifact@v3
     with:
       name: vozved
       path: |
         ./prog/prog.txt
         
   - name: download-artifact v1
     uses: actions/download-artifact@v3
     with:
       name: vozved
       path: ./artifact
   
